// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtnA0wZLFynr-oZ73OmsjTPU31ZryQ0GY',
    appId: '1:673146141536:web:a21789e6c3d52b1ccf7c05',
    messagingSenderId: '673146141536',
    projectId: 'school-poc-41f75',
    authDomain: 'school-poc-41f75.firebaseapp.com',
    storageBucket: 'school-poc-41f75.firebasestorage.app',
    measurementId: 'G-H5L1JHWJ4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxB09wxlPbRXtz1SMzYznf4K77wYY1e7M',
    appId: '1:673146141536:android:01313fe41e608a25cf7c05',
    messagingSenderId: '673146141536',
    projectId: 'school-poc-41f75',
    storageBucket: 'school-poc-41f75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCds1JNJcosWR0J9ZRzo_1vH-bRhtVJQO8',
    appId: '1:673146141536:ios:65504724653187aacf7c05',
    messagingSenderId: '673146141536',
    projectId: 'school-poc-41f75',
    storageBucket: 'school-poc-41f75.firebasestorage.app',
    iosBundleId: 'com.example.schoolPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCds1JNJcosWR0J9ZRzo_1vH-bRhtVJQO8',
    appId: '1:673146141536:ios:65504724653187aacf7c05',
    messagingSenderId: '673146141536',
    projectId: 'school-poc-41f75',
    storageBucket: 'school-poc-41f75.firebasestorage.app',
    iosBundleId: 'com.example.schoolPoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtnA0wZLFynr-oZ73OmsjTPU31ZryQ0GY',
    appId: '1:673146141536:web:1002e4e9c57de4a4cf7c05',
    messagingSenderId: '673146141536',
    projectId: 'school-poc-41f75',
    authDomain: 'school-poc-41f75.firebaseapp.com',
    storageBucket: 'school-poc-41f75.firebasestorage.app',
    measurementId: 'G-9BF0D32RZN',
  );
}
